### ISSUE TITLE
Pointless Releases

### ISSUE THREAD

**Issue by MotoAcidic** [livenodescoin/livenodes#2]
What is the need to add a checkpoint and change the protocol version and keep releasing update after update with no actual code changes?

**Comment by livenodescoin** [comment]
Crex24 exchange did a server update, during which livenodes wallets had issues, we have cooperated with them and released a new wallet that solved their issue.

**Comment by MotoAcidic** [comment]
A full understanding of how sporks work would help with the update as well since you didnt change the spork to enforce the update so they will fail again anyways.
